# Generated by Django 5.0
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='LifeEventTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(
                    choices=[
                        ('career', 'Career & Employment'),
                        ('housing', 'Housing & Living'),
                        ('family', 'Family & Relationships'),
                        ('education', 'Education'),
                        ('health', 'Health & Insurance'),
                        ('financial', 'Financial Milestones'),
                        ('retirement', 'Retirement Planning'),
                    ],
                    max_length=30
                )),
                ('icon', models.CharField(default='calendar', max_length=50)),
                ('suggested_changes', models.JSONField(default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'life_event_templates',
                'ordering': ['category', 'display_order', 'name'],
            },
        ),
    ]
