# Generated by Django 5.2.10 on 2026-01-08 20:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scenario",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("is_baseline", models.BooleanField(default=False)),
                ("projection_months", models.PositiveIntegerField(default=60)),
                ("start_date", models.DateField()),
                (
                    "inflation_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.03"), max_digits=5
                    ),
                ),
                (
                    "investment_return_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.07"), max_digits=5
                    ),
                ),
                (
                    "salary_growth_rate",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0.03"), max_digits=5
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.household",
                    ),
                ),
                (
                    "parent_scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="scenarios.scenario",
                    ),
                ),
            ],
            options={
                "db_table": "scenarios",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioChange",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("add_income", "Add Income Source"),
                            ("modify_income", "Modify Income"),
                            ("remove_income", "Remove Income"),
                            ("add_expense", "Add Expense"),
                            ("modify_expense", "Modify Expense"),
                            ("remove_expense", "Remove Expense"),
                            ("add_asset", "Add Asset"),
                            ("modify_asset", "Modify Asset Value"),
                            ("sell_asset", "Sell Asset"),
                            ("add_debt", "Add Debt"),
                            ("modify_debt", "Modify Debt"),
                            ("payoff_debt", "Pay Off Debt"),
                            ("refinance", "Refinance"),
                            ("lump_sum_income", "One-time Income"),
                            ("lump_sum_expense", "One-time Expense"),
                            ("modify_401k", "Change 401(k) Contribution"),
                            ("modify_hsa", "Change HSA Contribution"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("effective_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("source_account_id", models.UUIDField(blank=True, null=True)),
                ("source_flow_id", models.UUIDField(blank=True, null=True)),
                ("parameters", models.JSONField(default=dict)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="scenarios.scenario",
                    ),
                ),
            ],
            options={
                "db_table": "scenario_changes",
                "ordering": ["effective_date", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioComparison",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="core.household",
                    ),
                ),
                (
                    "scenarios",
                    models.ManyToManyField(
                        related_name="comparisons", to="scenarios.scenario"
                    ),
                ),
            ],
            options={
                "db_table": "scenario_comparisons",
            },
        ),
        migrations.CreateModel(
            name="ScenarioProjection",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("projection_date", models.DateField()),
                ("month_number", models.PositiveIntegerField()),
                ("total_assets", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "total_liabilities",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("net_worth", models.DecimalField(decimal_places=2, max_digits=14)),
                ("liquid_assets", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "retirement_assets",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("total_income", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("net_cash_flow", models.DecimalField(decimal_places=2, max_digits=12)),
                ("dscr", models.DecimalField(decimal_places=3, max_digits=6)),
                ("savings_rate", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "liquidity_months",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("income_breakdown", models.JSONField(default=dict)),
                ("expense_breakdown", models.JSONField(default=dict)),
                ("asset_breakdown", models.JSONField(default=dict)),
                ("liability_breakdown", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projections",
                        to="scenarios.scenario",
                    ),
                ),
            ],
            options={
                "db_table": "scenario_projections",
                "ordering": ["month_number"],
                "unique_together": {("scenario", "month_number")},
            },
        ),
    ]
