# Generated by Django 6.0.1 on 2026-01-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0003_scenario_is_stress_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenariochange",
            name="change_type",
            field=models.CharField(
                choices=[
                    ("add_income", "Add Income Source"),
                    ("modify_income", "Modify Income"),
                    ("remove_income", "Remove Income"),
                    ("add_expense", "Add Expense"),
                    ("modify_expense", "Modify Expense"),
                    ("remove_expense", "Remove Expense"),
                    ("add_asset", "Add Asset"),
                    ("modify_asset", "Modify Asset Value"),
                    ("sell_asset", "Sell Asset"),
                    ("add_debt", "Add Debt"),
                    ("modify_debt", "Modify Debt"),
                    ("payoff_debt", "Pay Off Debt"),
                    ("refinance", "Refinance"),
                    ("lump_sum_income", "One-time Income"),
                    ("lump_sum_expense", "One-time Expense"),
                    ("modify_401k", "Change 401(k) Contribution"),
                    ("modify_hsa", "Change HSA Contribution"),
                    ("adjust_total_expenses", "Adjust Total Expenses"),
                    ("adjust_total_income", "Adjust Total Income"),
                    ("set_savings_transfer", "Set Savings Transfer"),
                    ("modify_withholding", "Modify Tax Withholding"),
                    ("modify_deductions", "Modify Tax Deductions"),
                    ("switch_employment_type", "Switch Employment Type"),
                    ("set_quarterly_estimates", "Set Quarterly Tax Estimates"),
                    ("override_assumptions", "Override Scenario Assumptions"),
                    ("adjust_interest_rates", "Adjust Interest Rates"),
                    ("adjust_investment_value", "Adjust Investment Value"),
                    ("override_inflation", "Override Inflation Rate"),
                    ("override_investment_return", "Override Investment Return"),
                    ("override_salary_growth", "Override Salary Growth"),
                ],
                max_length=30,
            ),
        ),
    ]
