# Generated by Django 6.0.1 on 2026-01-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0004_alter_scenariochange_change_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenariochange",
            name="source_flow_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
