# Generated by Django - merge migration

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0006_add_gin_indexes_for_json_fields'),
        ('scenarios', '0007_add_unique_constraint_template_name'),
    ]

    operations = [
    ]
