# Generated by Django 5.2.10 on 2026-01-19 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenarios", "0008_merge_migrations"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="lifeeventtemplate",
            name="template_changes_gin",
        ),
        migrations.RemoveIndex(
            model_name="realitychangeevent",
            name="reality_event_payload_gin",
        ),
        migrations.RemoveIndex(
            model_name="scenariochange",
            name="scenario_change_params_gin",
        ),
        migrations.AlterField(
            model_name="scenario",
            name="projection_months",
            field=models.PositiveIntegerField(
                default=120, validators=[django.core.validators.MaxValueValidator(360)]
            ),
        ),
        migrations.AlterField(
            model_name="scenariochange",
            name="effective_date",
            field=models.DateField(
                help_text="Date when this change takes effect (inclusive). Must be within the scenario's projection period."
            ),
        ),
        migrations.AlterField(
            model_name="scenariochange",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Optional date when this change stops applying (inclusive). For recurring changes (ADD_INCOME, ADD_EXPENSE), the change continues to apply through and including this date, then is removed starting the next month. Leave blank for changes that apply indefinitely. Example: For temporary income with end_date=2026-12-31, the income is included in December 2026 and removed starting January 2027.",
                null=True,
            ),
        ),
    ]
