# Generated by Django 6.0.1 on 2026-01-10 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserHelpState",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "active_tour_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("active_tour_step_index", models.PositiveIntegerField(default=0)),
                ("active_tour_started_at", models.DateTimeField(blank=True, null=True)),
                ("last_interaction_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_state",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Help State",
                "verbose_name_plural": "User Help States",
                "db_table": "help_user_state",
            },
        ),
        migrations.CreateModel(
            name="ArticleRead",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("article_id", models.CharField(db_index=True, max_length=200)),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                ("time_spent_seconds", models.PositiveIntegerField(default=0)),
                ("scroll_depth_percent", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles_read",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "help_article_read",
                "indexes": [
                    models.Index(
                        fields=["user", "article_id"],
                        name="help_articl_user_id_d42774_idx",
                    )
                ],
                "unique_together": {("user", "article_id")},
            },
        ),
        migrations.CreateModel(
            name="HelpInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("tour_started", "Tour Started"),
                            ("tour_step_viewed", "Tour Step Viewed"),
                            ("tour_completed", "Tour Completed"),
                            ("tour_skipped", "Tour Skipped"),
                            ("tour_dismissed", "Tour Dismissed"),
                            ("article_viewed", "Article Viewed"),
                            ("article_completed", "Article Completed"),
                            ("tooltip_opened", "Tooltip Opened"),
                            ("insight_viewed", "Insight Viewed"),
                            ("insight_action_clicked", "Insight Action Clicked"),
                            ("insight_dismissed", "Insight Dismissed"),
                            ("help_searched", "Help Searched"),
                            ("path_started", "Path Started"),
                            ("path_completed", "Path Completed"),
                            ("drawer_opened", "Drawer Opened"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("resource_type", models.CharField(blank=True, max_length=50)),
                ("resource_id", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="help_interactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "help_interaction",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="help_intera_user_id_6b2883_idx",
                    ),
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="help_intera_event_t_865943_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InsightDismissal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("insight_rule_id", models.CharField(db_index=True, max_length=100)),
                ("dismissed_at", models.DateTimeField(auto_now_add=True)),
                ("is_permanent", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_dismissals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "help_insight_dismissal",
                "indexes": [
                    models.Index(
                        fields=["user", "insight_rule_id"],
                        name="help_insigh_user_id_07b5f2_idx",
                    )
                ],
                "unique_together": {("user", "insight_rule_id")},
            },
        ),
        migrations.CreateModel(
            name="LearningPathProgress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("path_id", models.CharField(db_index=True, max_length=100)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("current_item_index", models.PositiveIntegerField(default=0)),
                ("total_items", models.PositiveIntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_path_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "help_learning_path_progress",
                "indexes": [
                    models.Index(
                        fields=["user", "path_id"],
                        name="help_learni_user_id_b560fa_idx",
                    )
                ],
                "unique_together": {("user", "path_id")},
            },
        ),
        migrations.CreateModel(
            name="TourCompletion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tour_id", models.CharField(db_index=True, max_length=100)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("steps_completed", models.PositiveIntegerField(default=0)),
                ("total_steps", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "help_tour_completion",
                "indexes": [
                    models.Index(
                        fields=["user", "tour_id"],
                        name="help_tour_c_user_id_6485a8_idx",
                    )
                ],
                "unique_together": {("user", "tour_id")},
            },
        ),
    ]
