# Generated by Django 5.0
import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('net_worth_market', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_worth_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('monthly_surplus', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dscr', models.DecimalField(decimal_places=3, max_digits=6)),
                ('liquidity_months', models.DecimalField(decimal_places=2, max_digits=5)),
                ('savings_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('dti_ratio', models.DecimalField(decimal_places=4, max_digits=5)),
                ('debt_to_asset_market', models.DecimalField(decimal_places=4, max_digits=5)),
                ('debt_to_asset_cost', models.DecimalField(decimal_places=4, max_digits=5)),
                ('weighted_avg_interest_rate', models.DecimalField(decimal_places=5, max_digits=7)),
                ('high_interest_debt_ratio', models.DecimalField(decimal_places=4, max_digits=5)),
                ('housing_ratio', models.DecimalField(decimal_places=4, max_digits=5)),
                ('fixed_expense_ratio', models.DecimalField(decimal_places=4, max_digits=5)),
                ('essential_expense_ratio', models.DecimalField(decimal_places=4, max_digits=5)),
                ('income_concentration', models.DecimalField(decimal_places=4, max_digits=5)),
                ('unrealized_gains', models.DecimalField(decimal_places=2, max_digits=14)),
                ('investment_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('total_assets_market', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_assets_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_liabilities', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_monthly_expenses', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_debt_service', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_liquid_assets', models.DecimalField(decimal_places=2, max_digits=14)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricsnapshots', to='core.household')),
            ],
            options={
                'db_table': 'metric_snapshots',
                'ordering': ['-as_of_date'],
                'unique_together': {('household', 'as_of_date')},
            },
        ),
        migrations.CreateModel(
            name='MetricThreshold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=50)),
                ('warning_threshold', models.DecimalField(decimal_places=4, max_digits=10)),
                ('critical_threshold', models.DecimalField(decimal_places=4, max_digits=10)),
                ('comparison', models.CharField(choices=[('lt', 'Less than'), ('gt', 'Greater than')], max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricthresholds', to='core.household')),
            ],
            options={
                'db_table': 'metric_thresholds',
                'unique_together': {('household', 'metric_name')},
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info'), ('positive', 'Positive')], max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True)),
                ('metric_name', models.CharField(blank=True, max_length=50)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='core.household')),
            ],
            options={
                'db_table': 'insights',
                'ordering': ['-created_at'],
            },
        ),
    ]
