# Generated by Django 6.0.1 on 2026-01-10 04:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_email"),
        ("goals", "0001_initial"),
        ("scenarios", "0004_alter_scenariochange_change_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalSolution",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("options", models.JSONField(default=dict)),
                ("plan", models.JSONField(default=list)),
                ("result", models.JSONField(default=dict)),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "goal_solutions",
                "ordering": ["-computed_at"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="goal",
            name="unique_primary_goal_per_household",
        ),
        migrations.AlterField(
            model_name="goal",
            name="goal_type",
            field=models.CharField(
                choices=[
                    ("emergency_fund_months", "Emergency Fund (Months)"),
                    ("min_dscr", "Minimum DSCR"),
                    ("min_savings_rate", "Minimum Savings Rate"),
                    ("net_worth_target", "Net Worth Target"),
                    ("net_worth_target_by_date", "Net Worth Target by Date"),
                    ("retirement_age", "Retirement Age"),
                    ("debt_free_date", "Debt-Free Date"),
                    ("custom", "Custom Goal"),
                ],
                db_index=True,
                help_text="Type of goal which determines how target_value is interpreted",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="core.household",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="target_date",
            field=models.DateField(
                blank=True,
                help_text="Target date for time-bound goals like net_worth_target",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="goal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True), ("is_primary", True)),
                fields=("household",),
                name="unique_primary_goal_per_household",
            ),
        ),
        migrations.AddField(
            model_name="goalsolution",
            name="applied_scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="goal_solutions",
                to="scenarios.scenario",
            ),
        ),
        migrations.AddField(
            model_name="goalsolution",
            name="goal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solutions",
                to="goals.goal",
            ),
        ),
    ]
