# Generated by Django 5.0
import uuid
from decimal import Decimal
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetgroups', to='core.household')),
            ],
            options={
                'db_table': 'asset_groups',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('checking', 'Checking Account'), ('savings', 'Savings Account'), ('money_market', 'Money Market Account'), ('cd', 'Certificate of Deposit'), ('cash', 'Cash on Hand'), ('payroll_clearing', 'Payroll Clearing'), ('brokerage', 'Brokerage Account'), ('crypto', 'Cryptocurrency'), ('traditional_401k', '401(k) - Traditional'), ('roth_401k', '401(k) - Roth'), ('traditional_ira', 'IRA - Traditional'), ('roth_ira', 'IRA - Roth'), ('sep_ira', 'SEP IRA'), ('simple_ira', 'SIMPLE IRA'), ('tsp', 'TSP (Federal)'), ('pension', 'Pension'), ('annuity', 'Annuity'), ('hsa', 'Health Savings Account'), ('primary_residence', 'Primary Residence'), ('rental_property', 'Rental Property'), ('vacation_property', 'Vacation Property'), ('land', 'Land'), ('commercial_property', 'Commercial Property'), ('vehicle', 'Vehicle'), ('boat', 'Boat/RV'), ('jewelry', 'Jewelry/Collectibles'), ('other_asset', 'Other Asset'), ('business_equity', 'Business Ownership/Equity'), ('accounts_receivable', 'Accounts Receivable'), ('loans_receivable', 'Loans to Others'), ('tax_refund', 'Expected Tax Refund'), ('credit_card', 'Credit Card'), ('store_card', 'Store Credit Card'), ('heloc', 'Home Equity Line of Credit'), ('personal_loc', 'Personal Line of Credit'), ('business_loc', 'Business Line of Credit'), ('primary_mortgage', 'Primary Residence Mortgage'), ('rental_mortgage', 'Rental Property Mortgage'), ('second_mortgage', 'Second Mortgage'), ('auto_loan', 'Auto Loan'), ('personal_loan', 'Personal Loan'), ('student_loan_federal', 'Federal Student Loan'), ('student_loan_private', 'Private Student Loan'), ('boat_loan', 'Boat/RV Loan'), ('medical_debt', 'Medical Debt'), ('tax_debt', 'Tax Debt Owed'), ('family_loan', 'Loan from Family/Friends'), ('other_liability', 'Other Liability')], max_length=30)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('account_number_last4', models.CharField(blank=True, max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('employer_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('asset_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounts.assetgroup')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.household')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='core.householdmember')),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BalanceSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_of_date', models.DateField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='accounts.account')),
            ],
            options={
                'db_table': 'balance_snapshots',
                'ordering': ['-as_of_date', '-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='LiabilityDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interest_rate', models.DecimalField(decimal_places=5, help_text='As decimal: 0.065 = 6.5%. Maximum 100% (1.0)', max_digits=7, validators=[MinValueValidator(Decimal('0')), MaxValueValidator(Decimal('1.0'))])),
                ('rate_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], default='fixed', max_length=20)),
                ('original_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('origination_date', models.DateField(blank=True, null=True)),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('term_months', models.PositiveIntegerField(blank=True, null=True)),
                ('minimum_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_day_of_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[MinValueValidator(1), MaxValueValidator(31)])),
                ('is_interest_only', models.BooleanField(default=False)),
                ('includes_escrow', models.BooleanField(default=False)),
                ('escrow_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('rate_index', models.CharField(blank=True, max_length=50)),
                ('rate_margin', models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True)),
                ('rate_floor', models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True)),
                ('rate_ceiling', models.DecimalField(blank=True, decimal_places=5, max_digits=7, null=True)),
                ('servicer', models.CharField(blank=True, max_length=200)),
                ('is_income_driven', models.BooleanField(default=False)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liability_details', to='accounts.account')),
            ],
            options={
                'db_table': 'liability_details',
            },
        ),
        migrations.CreateModel(
            name='AssetDetails',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('property_type', models.CharField(blank=True, max_length=50)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('square_footage', models.PositiveIntegerField(blank=True, null=True)),
                ('lot_size_acres', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('year_built', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_property_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('annual_insurance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('annual_hoa', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monthly_rent_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('vin', models.CharField(blank=True, max_length=17)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asset_details', to='accounts.account')),
            ],
            options={
                'db_table': 'asset_details',
            },
        ),
        migrations.AddIndex(
            model_name='balancesnapshot',
            index=models.Index(fields=['account', '-as_of_date'], name='balance_snapshot_account_as_of_date'),
        ),
    ]
