# Generated by Django 5.2.10 on 2026-01-08 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="core.household",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="core.householdmember",
            ),
        ),
        migrations.AddField(
            model_name="assetdetails",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="asset_details",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="assetgroup",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="core.household",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="asset_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="accounts.assetgroup",
            ),
        ),
        migrations.AddField(
            model_name="balancesnapshot",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="liabilitydetails",
            name="account",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liability_details",
                to="accounts.account",
            ),
        ),
        migrations.AddIndex(
            model_name="balancesnapshot",
            index=models.Index(
                fields=["account", "-as_of_date"], name="balance_sna_account_7960f5_idx"
            ),
        ),
    ]
