# Generated by Claude Code on 2026-01-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_household_alter_assetgroup_household"),
    ]

    operations = [
        migrations.AddField(
            model_name="liabilitydetails",
            name="in_forbearance",
            field=models.BooleanField(
                default=False,
                help_text="Indicates if payments are temporarily suspended (e.g., student loan forbearance or deferment)",
            ),
        ),
    ]
