# Generated by Django 5.2.10 on 2026-01-08 20:24

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome"),
                            ("household_info", "Household Info"),
                            ("members", "Members"),
                            ("tax_filing", "Tax Filing"),
                            ("income_sources", "Income Sources"),
                            ("business_expenses", "Business & Rental Expenses"),
                            ("withholding", "Withholding"),
                            ("pretax_deductions", "Pre-Tax Deductions"),
                            ("bank_accounts", "Bank Accounts"),
                            ("investments", "Investments"),
                            ("retirement", "Retirement Accounts"),
                            ("real_estate", "Real Estate"),
                            ("vehicles", "Vehicles"),
                            ("personal_property", "Personal Property"),
                            ("business_ownership", "Business Ownership"),
                            ("mortgages", "Mortgages"),
                            ("credit_cards", "Credit Cards"),
                            ("student_loans", "Student Loans"),
                            ("other_debts", "Other Debts"),
                            ("housing_expenses", "Housing Expenses"),
                            ("utilities", "Utilities"),
                            ("insurance", "Insurance"),
                            ("transportation", "Transportation"),
                            ("food", "Food"),
                            ("other_expenses", "Other Expenses"),
                            ("review", "Review"),
                            ("complete", "Complete"),
                        ],
                        default="welcome",
                        max_length=50,
                    ),
                ),
                (
                    "completed_steps",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "skipped_steps",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to="core.household",
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_progress",
            },
        ),
        migrations.CreateModel(
            name="OnboardingStepData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome"),
                            ("household_info", "Household Info"),
                            ("members", "Members"),
                            ("tax_filing", "Tax Filing"),
                            ("income_sources", "Income Sources"),
                            ("business_expenses", "Business & Rental Expenses"),
                            ("withholding", "Withholding"),
                            ("pretax_deductions", "Pre-Tax Deductions"),
                            ("bank_accounts", "Bank Accounts"),
                            ("investments", "Investments"),
                            ("retirement", "Retirement Accounts"),
                            ("real_estate", "Real Estate"),
                            ("vehicles", "Vehicles"),
                            ("personal_property", "Personal Property"),
                            ("business_ownership", "Business Ownership"),
                            ("mortgages", "Mortgages"),
                            ("credit_cards", "Credit Cards"),
                            ("student_loans", "Student Loans"),
                            ("other_debts", "Other Debts"),
                            ("housing_expenses", "Housing Expenses"),
                            ("utilities", "Utilities"),
                            ("insurance", "Insurance"),
                            ("transportation", "Transportation"),
                            ("food", "Food"),
                            ("other_expenses", "Other Expenses"),
                            ("review", "Review"),
                            ("complete", "Complete"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                ("is_valid", models.BooleanField(default=False)),
                ("validation_errors", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "progress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="step_data",
                        to="onboarding.onboardingprogress",
                    ),
                ),
            ],
            options={
                "db_table": "onboarding_step_data",
                "unique_together": {("progress", "step")},
            },
        ),
    ]
