# Generated by Django 5.0
import uuid
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeSource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('income_type', models.CharField(choices=[('w2', 'W-2 Employment'), ('w2_hourly', 'W-2 Hourly'), ('self_employed', 'Self-Employment (1099)'), ('rental', 'Rental Income'), ('investment', 'Investment Income'), ('retirement', 'Retirement/Pension'), ('social_security', 'Social Security'), ('other', 'Other Income')], max_length=30)),
                ('gross_annual_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('expected_annual_hours', models.PositiveIntegerField(blank=True, default=2080, null=True)),
                ('pay_frequency', models.CharField(choices=[('weekly', 'Weekly (52)'), ('biweekly', 'Bi-weekly (26)'), ('semimonthly', 'Semi-monthly (24)'), ('monthly', 'Monthly (12)')], default='biweekly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomesources', to='core.household')),
                ('household_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_sources', to='core.householdmember')),
            ],
            options={
                'db_table': 'income_sources',
            },
        ),
        migrations.CreateModel(
            name='W2Withholding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filing_status', models.CharField(choices=[('single', 'Single or Married Filing Separately'), ('married', 'Married Filing Jointly'), ('head_of_household', 'Head of Household')], default='single', max_length=30)),
                ('multiple_jobs_or_spouse_works', models.BooleanField(default=False)),
                ('child_tax_credit_dependents', models.PositiveSmallIntegerField(default=0)),
                ('other_dependents', models.PositiveSmallIntegerField(default=0)),
                ('other_income', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('extra_withholding', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('state_allowances', models.PositiveSmallIntegerField(default=0)),
                ('state_additional_withholding', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('income_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='w2_withholding', to='taxes.incomesource')),
            ],
            options={
                'db_table': 'w2_withholdings',
            },
        ),
        migrations.CreateModel(
            name='PreTaxDeduction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deduction_type', models.CharField(choices=[('traditional_401k', '401(k) Traditional'), ('roth_401k', '401(k) Roth'), ('traditional_403b', '403(b)'), ('tsp_traditional', 'TSP Traditional'), ('tsp_roth', 'TSP Roth'), ('hsa', 'HSA'), ('fsa_health', 'Healthcare FSA'), ('fsa_dependent', 'Dependent Care FSA'), ('health_insurance', 'Health Insurance'), ('dental_insurance', 'Dental Insurance'), ('vision_insurance', 'Vision Insurance'), ('life_insurance', 'Life Insurance'), ('commuter_transit', 'Commuter Transit'), ('commuter_parking', 'Commuter Parking'), ('other_pretax', 'Other Pre-Tax')], max_length=30)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('amount_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage')], default='fixed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employer_match_percentage', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('employer_match_limit_percentage', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('employer_match_limit_annual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('income_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pretax_deductions', to='taxes.incomesource')),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_deductions', to='accounts.account')),
            ],
            options={
                'db_table': 'pretax_deductions',
            },
        ),
        migrations.CreateModel(
            name='PostTaxDeduction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deduction_type', models.CharField(choices=[('roth_ira', 'Roth IRA'), ('life_insurance_post', 'Life Insurance'), ('union_dues', 'Union Dues'), ('garnishment', 'Wage Garnishment'), ('child_support', 'Child Support'), ('loan_repayment', '401(k) Loan'), ('charitable', 'Charitable'), ('other_posttax', 'Other')], max_length=30)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('amount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('income_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posttax_deductions', to='taxes.incomesource')),
            ],
            options={
                'db_table': 'posttax_deductions',
            },
        ),
        migrations.CreateModel(
            name='SelfEmploymentTax',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('q1_estimated_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('q2_estimated_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('q3_estimated_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('q4_estimated_payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('estimated_annual_expenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('retirement_contribution_percentage', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=5)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selfemploymenttaxs', to='core.household')),
                ('income_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='se_tax_config', to='taxes.incomesource')),
            ],
            options={
                'db_table': 'self_employment_tax',
            },
        ),
    ]
