# Generated by Django 6.0.1 on 2026-01-10 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_user_email"),
        ("taxes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incomesource",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="core.household",
            ),
        ),
        migrations.AlterField(
            model_name="selfemploymenttax",
            name="household",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to="core.household",
            ),
        ),
    ]
